# Generated by Django 5.0 on 2023-12-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=1)),
                ('release_date', models.DateField()),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
